### ISSUE TITLE
Open With...

### ISSUE THREAD

**Issue by Yomi0** [marcelhollerbach/jesus#10]
A couple issues. 

1. It lists GIMP and Ristretto multiple times. 
2. The icon is show to be mpv...
3. (minor) ```Set as default``` has escaped the box. 

![shot-2015-07-07_14-19-49](https://cloud.githubusercontent.com/assets/3170531/8553857/3c40b220-24b4-11e5-8b22-67bf53ea9137.png)

**Comment by marcelhollerbach** [comment]
@Yomi0 do you know erigo ? For the next time you want to prototype a ui look at it :)
