### ISSUE TITLE
make clean

### ISSUE THREAD

**Issue by Yomi0** [marcelhollerbach/jesus#3]
``` make: *** No rule to make target 'clean'.  Stop. ```

**Comment by marcelhollerbach** [comment]
Thats strange, I am using cmake to generate the makefiles, and cmake is generating the clean target here ... which cmake version ?

**Comment by Yomi0** [comment]
Name           : cmake
Version        : 3.2.3-1

OS : Arch Linux

**Comment by marcelhollerbach** [comment]
Okay yes thats the reason. Cmake has a build directory. This means every file which is created while compiling the Software is created in this build directory, the source dir stays clean. 

I think this can be closed :)

**Comment by marcelhollerbach** [comment]
... close ...
