### ISSUE TITLE
Sorting by name is case sensitive. 

### ISSUE THREAD

**Issue by Yomi0** [marcelhollerbach/jesus#7]
alphabetical sorting is not alphabetical...or more accurately...it is alphabetical, but the current sorting method seem to assume A is different from a. 

![shot-2015-07-06_16-18-56](https://cloud.githubusercontent.com/assets/3170531/8532275/05ca5c78-23fb-11e5-8947-b15c5f7bcb2f.png)

**Comment by mjtorn** [comment]
I haven't tested Jesus in a while, but I prefer case-sensitivity. 'A' most certainly is not 'a'. Maybe a conf option if you really want to go the other way with this?

**Comment by Yomi0** [comment]
> I haven't tested Jesus in a while, but I prefer case-sensitivity. 'A' most certainly is not 'a'. Maybe a conf option if you really want to go the other way with this?

Yeah, I guess a config option to ignore case would be useful.

**Comment by marcelhollerbach** [comment]
For now I just changed the sorting, but I will add the config option soon

**Comment by Yomi0** [comment]
> For now I just changed the sorting, but I will add the config option soon. 

Oh, thanks.

**Comment by marcelhollerbach** [comment]
done.
