### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Yomi0** [marcelhollerbach/jesus#9]
```Crtl + H```  This is a common shortcut for displaying hidden files. 
```Ctrl + Q``` Close Window. 
```Backspace``` For going back to the previous folder in the history.

**Comment by marcelhollerbach** [comment]
Implemented. :)

**Comment by Yomi0** [comment]
```Ctrl + R``` to reload. 
```Escape``` to close dialogs ?

**Comment by marcelhollerbach** [comment]
Ctrl + R : Its like you said, the library which is organizing files and etc. is monitor based. This means there is no reason for reloading :) 
Rest: agreed :)

**Comment by marcelhollerbach** [comment]
IN!! :)
